[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project.urls]
Homepage = "https://macq.planning.domains"
Documentation = "https://ai-planning.github.io/macq/"
