
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem model_blocks_prob)
    (:domain model_blocks_dom)

    (:objects
        
    )

    (:init
        
    )

    (:goal
        (and )
    )

    
    
    
)

