
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Domain file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (domain model_blocks_dom)
    (:requirements )
    (:types
        object
    )

    (:constants
        
    )

    (:predicates
        (on_object_object )
        (ontable_object )
        (clear_object )
        (handempty_ )
        (holding_object )
    )

    (:functions
        
    )

    

    
    (:action put-down_object
     :parameters ()
     :precondition (and (ontable_object ) (clear_object ) (holding_object ) (on_object_object ))
     :effect (and
        (on_object_object )
        (handempty_ ))
    )


    (:action unstack_object_object
     :parameters ()
     :precondition (and (handempty_ ) (ontable_object ))
     :effect (and
        (on_object_object )
        (holding_object )
        (ontable_object )
        (clear_object ))
    )


    (:action stack_object_object
     :parameters ()
     :precondition (and (on_object_object ) (holding_object ))
     :effect (and
        (clear_object )
        (ontable_object )
        (handempty_ ))
    )


    (:action pick-up_object
     :parameters ()
     :precondition (and (handempty_ ) (ontable_object ) (clear_object ) (on_object_object ))
     :effect (and
        (on_object_object ))
    )

)