
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem test)
    (:domain playlistmaker)

    (:objects
        classical_genre country_genre jazz_genre pop_genre rock_genre - genre
        classical_song classical_song_2 classical_song_3 jazz_song pop_song rock_song - song
    )

    (:init
        (in_playlist rock_song)
        (has_genre pop_song pop_genre)
        (has_genre classical_song classical_genre)
        (has_genre classical_song_2 classical_genre)
        (has_genre jazz_song jazz_genre)
        (has_genre classical_song_3 classical_genre)
        (has_genre rock_song rock_genre)
    )

    (:goal
        (and (in_playlist pop_song) (and (in_playlist jazz_song) (and (in_playlist classical_song) (and (in_playlist classical_song_2) (in_playlist classical_song_3)))))
    )

    
    
    
)

