
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Domain file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (domain playlistmaker)
    (:requirements :equality :typing)
    (:types
        genre - object
        song - object
    )

    (:constants
        
    )

    (:predicates
        (in_playlist ?x1 - song)
        (on ?x1 - song ?x2 - song)
        (has_genre ?x1 - song ?x2 - genre)
        (empty )
    )

    (:functions
        
    )

    

    
    (:action add_song
     :parameters (?add - song ?prev - song ?genre1 - genre ?genre2 - genre)
     :precondition (and (and (and (and (not (in_playlist ?add)) (in_playlist ?prev)) (has_genre ?add ?genre1)) (has_genre ?prev ?genre2)) (not (= ?genre1 ?genre2)))
     :effect (and
        (in_playlist ?add)
        (on ?prev ?add))
    )


    (:action add_first_song
     :parameters (?add - song)
     :precondition (empty )
     :effect (and
        (in_playlist ?add)
        (not (empty )))
    )


    (:action empty_test
     :parameters ()
     :precondition (empty )
     :effect (and
        (empty ))
    )

)