
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem log00_x)
    (:domain logistics)

    (:objects
        
    )

    (:init
        
    )

    (:goal
        (and )
    )

    
    
    
)

