---
metadata:
  acronym: MACQ
  name: Model Learning for AI Planning
  title_text: 'MACQ: A Holistic View of Model Acquisition Techniques'
  citation_text: "@inproceedings{macq, \n title={{MACQ: A Holistic View of Model\n\t Acquisition Techniques}}, \n author={Ethan Callanan, Rebecca De Venezia,\n\t Victoria Armstrong, Alison Paredes,\n\t Tathagata Chakraborti, and\n\t Christian Muise}, \n booktitle={ICAPS Workshop on Knowledge \n\t    Engineering for Planning \n\t    and Scheduling (KEPS)}, \n
    year={2022}}"
  link_to_contribute: https://github.com/AI-Planning/macq
  link_to_code: https://github.com/TathagataChakraborti/survey-visualizer
  primary_link: https://drive.google.com/file/d/1WqO-PWbE7uhHVbSRnqGcJkQN2-Hpquh2/view?usp=sharing
  secondary_links: 
    - name: Arora et al. 2019
      link: https://hal.archives-ouvertes.fr/hal-02010536/file/A_Review_of_Learning_Planning_Action_Models.pdf
    - name: Jilani et al. 2014
      link: http://eprints.hud.ac.uk/id/eprint/20380/
    - name: Jimenez et al. 2012
      link: https://www.cambridge.org/core/journals/knowledge-engineering-review/article/abs/review-of-machine-learning-for-automated-planning/F641360D1F0461D0B323C8A299DBE61E
  community_link: https://join.slack.com/t/theplanningcommunity/shared_invite/enQtNjg0MTIzNTE3MTY4LTQ4YTRiNjhjNmVlNmEwMGMxOTQwNTZlYWM2YTk1YjdkZmIyMTU5MzRjZjYzOWYxMjJkNGM3YTM2MWI0MmM2MGY
  info_tile: true
  info_text: Interested in model acquistion for AI planning? Learn more about the MACQ package at upcoming venus 
  info_link:
  - link: http://icaps22.icaps-conference.org/workshops/KEPS
    text: KEPS 2022
  - link: http://ieeevis.org/year/2022/welcome
    text: IEEEVIS 2022
link_to_server: https://toby.mua8gtem6c8.us-east.codeengine.appdomain.cloud
default_view: Taxonomy
min_year: 1984
views:
- name: Taxonomy
  disabled: false
  default_tab: Taxonomy
  tabs:
  - tab_name: Taxonomy
    disabled: false
    fancy_chart: true
    fancy_chart_default_level: 2
    input_file:
      filename: /Users/tchakra2/Desktop/temp/slug.xlsx
      active_worksheet: slug
    papers_list:
      shuffle_list: true 
      key_map:
        slug: 0
        title: 2
        abstract: 5
        authors: 4
        venue: 6
        sessions:
        year: 7
        keywords:
        link: 3
      rows:
        start: 5
        stop: 48
        exclude:
          - 39
    taxonomy:
      rows:
        start: 1
        stop: 4
      columns:
        start: 11
        stop: 40
- name: Affinity
  disabled: false
- name: Network
  files_directory: /path/to/pdfs
  match_threshold: 0.25
  disabled: false
- name: Insights
  disabled: false

